apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: nginx
      image: yashassamaga/multi-worker
      ports:
        - containerPort: 3000